# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types:
      - created
      
jobs:
  build:
    name: 'Build Ghidra extension'
    strategy:
      matrix:
        ghidra:
          - version: "10.0"
          - version: "10.0.0-beta"
          - version: "9.2.4"
          - version: "9.2.2"
          - version: "9.2.1"
          - version: "9.2"
          - version: "9.1.2"
    runs-on: "ubuntu-latest"
    container: registry.gitlab.com/clienthax1/ghidra-container/ghidra-plugin-builder:${{ matrix.ghidra.version }}
    steps:
      - name: "Clone"
        uses: actions/checkout@v2
      - name: "Compile - ${{ matrix.ghidra.version }}"
        run: |
          gradle
          ls -lah dist/
      - name: "Upload - ${{ matrix.ghidra.version }}"
        uses: actions/upload-artifact@v2
        with:
          name: ghidra_${{ matrix.ghidra.version }}_Ps3GhidraScripts
          path: |
            README.md
            dist/*.zip
